defaults:
  - dataset: kitti360
  - pose_estimation: orb-slam
  - reconstruction: simple
  - splatting: slam


dataset_name: ""
exp_name: "debug"

extract_frames:
  skip: False
  video_path: ""

colmap:
  skip: False

precomputation:
  depth: True
  normal: True

pose_estimation:
  skip: True # not implemented yet, please provide estimated poses

scale_alignment:
  skip: False

create_pointcloud:
  skip: False

train_gaussians:
  skip: False

